image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - dotnet build

test-job:
  stage: test
  script:
    - dotnet test
    - echo "Running unit tests... This will take about 5 seconds."
    - sleep 4

deploy-job:
  stage: deploy
  script:
    - dotnet publish -c Release -o publish
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  artifacts:
    paths:
      - publish
